import type { TableZone } from "./canvas";
import type { SubwayActionType } from "./config";

export type Lesson = {title:string; phase:string; zone:TableZone; text:string; task:string; actions?:SubwayActionType[]; art:"map"|"recipe"|"cards"|"schedule"|"crossing"};
export const SUBWAY_LESSONS: Lesson[] = [
  {title:"Welcome to the city",phase:"PROCUREMENT",zone:"table",art:"map",text:"Build three subway routes, connect stations and deliver secret goals. Most points wins—not the longest line. This is an isolated practice table; nothing here changes a saved game.",task:"Drag the table, then zoom with the + / − buttons. Next takes a closer look."},
  {title:"Read the pegboard",phase:"PROCUREMENT",zone:"board",art:"map",text:"Each hole is a possible peg. Named stations move between games but stay spaced apart. Major stations have three docks; minor stations have two. Colours and letter codes identify routes. The printed geography is decorative.",task:"Find one major and one minor station. Use Board to return here any time."},
  {title:"Sign your routes",phase:"PROCUREMENT",zone:"office",art:"recipe",text:"Choose one route at its printed price. There are as many choices as players, refilled after each pick. Everyone drafts three routes. Order reverses each round; passing and discounts are gone. The recipe is read left to right: one segment per number, not a total distance.",task:"Open any contract, read its recipe and special, then sign it.",actions:["PROCURE"]},
  {title:"Choose a face-up card",phase:"CARD_DRAFT",zone:"office",art:"cards",text:"After routes, everyone drafts six cards, one per turn. Engineering cards include both goals and Destinations. Construction cards help during building. Every held goal can score; choose any mix. Two cards from each category are face up and refill immediately.",task:"Open a named face-up card and draft it. Read the effect before choosing.",actions:["DRAFT_CARD"]},
  {title:"Try a blind draw",phase:"CARD_DRAFT",zone:"office",art:"cards",text:"You may instead draw a random card from any category. There is no minimum per category. Engineering goals and Destinations have one copy each across the table. Construction cards can repeat. When a blind pile is empty, take a remaining face-up card.",task:"Open a Blind draw option and draw a random card.",actions:["DRAFT_CARD"]},
  {title:"Your goals stay flexible",phase:"BUY_SURVEYS",zone:"hand",art:"cards",text:"Every Engineering goal and Destination in your hand can score. You do not commit cards or assign them to routes. Any of your routes can satisfy a Destination, while each Engineering card explains its company-wide condition. Goals remain private until results.",task:"Open your goals and inspect their requirements. There is nothing to lock."},
  {title:"Optional surveys",phase:"BUY_SURVEYS",zone:"hand",art:"map",text:"After the six-card draft, optionally buy up to five Survey Pins for $1M each. A pin scores +1 VP when your own network has a node there. Pins reserve nothing. Players place purchased pins before placing route starters.",task:"Choose a quantity, including zero, and confirm the purchase.",actions:["BUY_SURVEYS"]},
  {title:"Hire crews for this round",phase:"CONSTRUCTION",zone:"schedule",art:"schedule",text:"There is no advance timetable. Each round, hire zero to three crews, on different unfinished routes: $1M for one, $3M for two, $6M for three. Each hired crew builds one segment. You can change which routes you activate next round. Starting cash is $60M; debt is allowed but costs −4 VP per $1M owed at the end.",task:"Resolve any opening priority opportunity, choose your routes, inspect the bill, then hire.",actions:["HIRE_CREWS"]},
  {title:"Play one card",phase:"CONSTRUCTION",zone:"schedule",art:"cards",text:"You may play one Construction card per round; it is discarded. Priority Dispatch has an opening window in rotating order, before anyone acts. The first claimant takes first turn and uses their card allowance. Advance Booking reserves $1M off next round; Relief Crew waives the first $1M now. Discounts expire unused and never pay cash.",task:"Read the cards at Crew dispatch. If you hold Priority Dispatch, claim it or keep it. Check each card's timing before hiring."},
  {title:"Start at the edge",phase:"STARTER_PLACEMENT",zone:"board",art:"recipe",text:"Every purchased route gets one free starter peg. It must be on a non-station hole on the outer border. Select a highlighted target, inspect the preview, then Confirm. Tapping a hole alone never spends your placement.",task:"Place a starter using the actual board and Confirm button.",actions:["PLACE_STARTER"]},
  {title:"Build, inspect, undo",phase:"CONSTRUCTION",zone:"board",art:"recipe",text:"Follow the next printed length, allowing half a peg of tolerance. Turns may be at most 90°. Glowing targets are legal; an illegal target explains the problem. Confirm spends one action. Undo restores the latest placement and payments until another accepted action occurs.",task:"Use Crews to hire, then Board to inspect a target. Confirm a legal build and try Undo. Your seat stays selected so you can undo. Undo restores the placement and tolls; the hired crew remains paid.",actions:["BUILD","UNDO_PLACEMENT"]},
  {title:"Connections have consequences",phase:"CONSTRUCTION",zone:"board",art:"crossing",text:"Choose a specific free dock to connect a station; a full station is closed. Your line may visit a station only once. Crossing a line is allowed, but contact with another company's route costs $1M per contact, paid to its owner. Your own crossings count for Crossing Design but do not charge an opponent toll. Read the preview before confirming.",task:"Explore legal targets and the toll preview. Construction cards are optional, at most one per period."},
  {title:"Count what you delivered",phase:"RESULTS",zone:"results",art:"map",text:"Score completed routes and their printed specials, stations, all held Engineering goals and Destinations and fulfilled surveys. Unfinished contracts and remaining debt lose points. Results show the breakdown: check what actually scored before planning your next game.",task:"Inspect the score sheets. Replay any lesson, or return to your game."},
];

export function lessonForPhase(phase:string, step:string):number {
  if(phase==="PROCUREMENT")return 2;
  if(phase==="ENGINEERING")return step==="CARD_DRAFT"?3:6;
  if(phase==="SCHEDULING")return 7;
  if(phase==="STARTER_PLACEMENT")return 9;
  if(phase==="CONSTRUCTION")return 7;
  return phase==="RESULTS"||phase==="SCORING"?12:0;
}
