import type { TableZone } from "./canvas";
import type { SubwayActionType } from "./config";

export type Lesson = {title:string; phase:string; zone:TableZone; text:string; task:string; actions?:SubwayActionType[]; art:"map"|"recipe"|"cards"|"schedule"|"crossing"};
export const SUBWAY_LESSONS: Lesson[] = [
  {title:"Welcome to the city",phase:"PROCUREMENT",zone:"table",art:"map",text:"Build three subway routes, connect neighborhoods and deliver secret goals. Most points wins—not the longest line. This is an isolated practice table; nothing here changes a saved game.",task:"Drag the table, then zoom with the + / − buttons. Next takes a closer look."},
  {title:"Read the pegboard",phase:"PROCUREMENT",zone:"board",art:"map",text:"Each hole is a possible peg. Ten neighborhoods change position and shape between games: three small (6 holes, 5 VP), six large (16 holes, 2 VP), and one medium (10 holes, 3 VP). Place a peg anywhere inside to serve one. There are no dock limits. Colours and letter codes identify routes. The printed geography is decorative.",task:"Find one large and one small neighborhood. Use Board to return here any time."},
  {title:"Sign your routes",phase:"PROCUREMENT",zone:"office",art:"recipe",text:"Choose one route at its printed price. There are as many choices as players, refilled after each pick. Everyone drafts three routes. Order reverses each round; passing and discounts are gone. The recipe is read left to right: one segment per number, not a total distance.",task:"Open any contract, read its recipe and completion points, then sign it.",actions:["PROCURE"]},
  {title:"Choose a face-up card",phase:"CARD_DRAFT",zone:"office",art:"cards",text:"Everyone receives two private Destination missions at game start. After routes, draft three Engineering goals, one per turn. Choose one of two face-up goals or draw blind. All three goals can score.",task:"Open a named face-up card and draft it. Read the effect before choosing.",actions:["DRAFT_CARD"]},
  {title:"Try a blind draw",phase:"CARD_DRAFT",zone:"office",art:"cards",text:"Draw a random Engineering goal instead of choosing a face-up goal. Each of the 16 Engineering cards occurs once. Destination missions are dealt separately.",task:"Open a Blind draw option and draw a random card.",actions:["DRAFT_CARD"]},
  {title:"Your goals stay flexible",phase:"BUY_SURVEYS",zone:"hand",art:"cards",text:"Every Engineering goal and Destination in your hand can score. You do not commit cards or assign them to routes. Destination neighborhoods must connect through your own network. Transfer at shared neighborhoods or pegs; disconnected routes and crossings do not join. Each Engineering card states its condition. Goals remain private until results.",task:"Open your goals and inspect their requirements. There is nothing to lock."},
  {title:"Optional surveys",phase:"BUY_SURVEYS",zone:"hand",art:"map",text:"After the three-card draft, optionally buy up to five Survey Pins for $1M each. A pin scores +1 VP when your own network has a node there. Pins reserve nothing. Players place purchased pins before placing route starters.",task:"Choose a quantity, including zero, and confirm the purchase.",actions:["BUY_SURVEYS"]},
  {title:"Hire crews for this round",phase:"CONSTRUCTION",zone:"schedule",art:"schedule",text:"Each round, hire zero to three crews on different unfinished routes: $1M for one, $3M for two, $6M for three. Each crew builds one segment. There are nine rounds. Starting cash is $40M; each completed line immediately pays $3M. Debt is allowed but costs −4 VP per $1M owed at the end.",task:"Choose your routes, inspect the bill, then hire.",actions:["HIRE_CREWS"]},
  {title:"Add a destination",phase:"CONSTRUCTION",zone:"schedule",art:"cards",text:"Before hiring crews on your turn, you may spend $5M for one extra random Destination mission, once per game. A two-neighborhood mission pays 4 VP; a three-neighborhood mission pays 7 VP. All its neighborhoods must connect through your company network. Unfinished lines can contribute.",task:"Read your missions under Cards. At Construction schedule, decide whether to buy an extra mission before hiring."},
  {title:"Start at the edge",phase:"STARTER_PLACEMENT",zone:"board",art:"recipe",text:"Every purchased route gets one free starter peg. It must be on a non-neighborhood hole on the outer border. Select a highlighted target, inspect the preview, then Confirm. Tapping a hole alone never spends your placement.",task:"Place a starter using the actual board and Confirm button.",actions:["PLACE_STARTER"]},
  {title:"Build, inspect, undo",phase:"CONSTRUCTION",zone:"board",art:"recipe",text:"Follow the next printed length, allowing half a peg of tolerance. Turns may be at most 90°. Glowing targets are legal; an illegal target explains the problem. Confirm spends one action. Undo restores the latest placement and payments until another accepted action occurs.",task:"Use Crews to hire, then Board to inspect a target. Confirm a legal build and try Undo. Your seat stays selected so you can undo. Undo restores the placement and tolls; the hired crew remains paid.",actions:["BUILD","UNDO_PLACEMENT"]},
  {title:"Connections have consequences",phase:"CONSTRUCTION",zone:"board",art:"crossing",text:"Place a node inside any neighborhood to serve it. Shared neighborhoods connect your own lines even at different holes. Repeated visits never multiply points. Crossing another color is allowed, but your line cannot cross itself, but contact with another company's route costs $1M per contact, paid to its owner. Your own contacts are free. A geometric crossing alone does not transfer passengers; your routes must share a neighborhood or peg.",task:"Explore the legal neighborhood holes. Inspect your network connections before confirming."},
  {title:"Count what you delivered",phase:"RESULTS",zone:"results",art:"map",text:"Score completed routes, neighborhoods, Engineering goals, connected Destination missions and fulfilled surveys. The longest continuous company route earns 5 VP (3 each if tied), measured in peg spaces without reusing a segment. Unfinished contracts and remaining debt lose points. Results show the breakdown: check what actually scored before planning your next game.",task:"Inspect the score sheets. Replay any lesson, or return to your game."},
];

export function lessonForPhase(phase:string, step:string):number {
  if(phase==="PROCUREMENT")return 2;
  if(phase==="ENGINEERING")return step==="CARD_DRAFT"?3:6;
  if(phase==="SCHEDULING")return 7;
  if(phase==="STARTER_PLACEMENT")return 9;
  if(phase==="CONSTRUCTION")return 7;
  return phase==="RESULTS"||phase==="SCORING"?12:0;
}
