import type { TableZone } from "./canvas";
import type { SubwayActionType } from "./config";

export type Lesson = {title:string; phase:string; zone:TableZone; text:string; task:string; actions?:SubwayActionType[]; art:"map"|"recipe"|"cards"|"schedule"|"crossing"};
export const SUBWAY_LESSONS: Lesson[] = [
  {title:"Welcome to the city",phase:"PROCUREMENT",zone:"table",art:"map",text:"Build three subway lines, connect neighborhoods and deliver secret goals. Most points wins—not the longest line. This is an isolated practice table; nothing here changes a saved game.",task:"Drag the table, then zoom with the + / − buttons. Next takes a closer look."},
  {title:"Read the pegboard",phase:"PROCUREMENT",zone:"board",art:"map",text:"Each hole is a possible peg. Ten neighborhoods change position and shape between games: three small (6 holes), six large (16 holes), and one medium (10 holes). Place a peg anywhere inside to serve one for your goals; neighborhoods award no automatic VP. There are no dock limits. Colours and letter codes identify lines. North is top, south bottom, west left, east right. Only the four extreme corner pegs are corners. Each station counts toward one side when different sides are required.",task:"Find one large and one small neighborhood. Use Board to return here any time."},
  {title:"Sign your lines",phase:"PROCUREMENT",zone:"office",art:"recipe",text:"Choose one line at its printed price. There are as many choices as players, refilled after each pick. Everyone drafts three lines from seven/ten/thirteen contracts at two/three/four players; one stays unused, so the final pick offers two choices. Players alternate in the same cyclic order; passing and discounts are gone. The recipe is read left to right: one segment per number, not a total distance.",task:"Open any contract, read its recipe and completion points, then sign it.",actions:["PROCURE"]},
  {title:"Choose a face-up card",phase:"CARD_DRAFT",zone:"office",art:"cards",text:"Everyone receives one two-neighborhood and one three-neighborhood Destination at game start, from a 30-card deck. After lines, draft three Engineering goals, one per turn. Choose one of two face-up goals or draw blind. All three goals can score.",task:"Open a named face-up card and draft it. Read the effect before choosing.",actions:["DRAFT_CARD"]},
  {title:"Try a blind draw",phase:"CARD_DRAFT",zone:"office",art:"cards",text:"Draw a random Engineering goal instead of choosing a face-up goal. Each of the 21 Engineering cards occurs once. Destination missions are dealt separately.",task:"Open a Blind draw option and draw a random card.",actions:["DRAFT_CARD"]},
  {title:"Your goals stay flexible",phase:"STARTER_PLACEMENT",zone:"hand",art:"cards",text:"Every Engineering goal and Destination in your hand can score. You do not commit cards or assign them to lines. Destination neighborhoods must connect through your own network. Transfer at horizontally/vertically adjacent stations on different lines of your company. Sharing an area, diagonal stations and string crossings do not join lines. The 21 Engineering cards have Line, Station and Neighborhood categories. Single Line means one line does all the work; Connected Network allows connected own lines; Company-wide permits disconnected lines. Line end means a starter or a completed final station. Cards score once at game end; live completion is provisional. Goals remain private until results.",task:"Open your goals and inspect their requirements. There is nothing to lock."},
  {title:"Hire crews for this round",phase:"CONSTRUCTION",zone:"schedule",art:"schedule",text:"Each round, hire zero to three crews on different unfinished lines: $1M for one, $3M for two, $6M for three. Each hired line gets one construction activation. This practice table uses straight segments; delayed-mode games may use an activation to stop at a bend and continue after hiring again. There are nine rounds. Starting cash is $40M; each completed line immediately pays $3M and each Destination mission pays $2M (pair) or $3M (triple) the moment your network connects it. You may borrow: crews and tolls can both take you below $0 on the turn you build. Your ending balance scores on a spectrum, from +2 VP at $4M or more down to −5 VP at −$4M or worse.",task:"Choose your lines, inspect the bill, then hire.",actions:["HIRE_CREWS"]},
  {title:"Add a destination",phase:"CONSTRUCTION",zone:"schedule",art:"cards",text:"Before hiring crews on your turn, you may spend $5M for one extra random Destination mission, once per game. A two-neighborhood mission pays 4 VP; a three-neighborhood mission pays 7 VP. All its neighborhoods must connect through your company network, in any order, with no starter or final station required there. Unfinished lines can contribute.",task:"Read your missions under Cards. At Construction schedule, decide whether to buy an extra mission before hiring."},
  {title:"Start at the edge",phase:"STARTER_PLACEMENT",zone:"board",art:"recipe",text:"Every purchased line gets one starter peg with no placement cost; joining an opponent station still pays its one-time access fee. It must be on an empty non-neighborhood hole on the outer border, never atop another peg—even your own. Select a highlighted target, inspect the preview, then Confirm. Tapping a hole alone never spends your placement.",task:"Place a starter using the actual board and Confirm button.",actions:["PLACE_STARTER"]},
  {title:"Build, inspect, undo",phase:"CONSTRUCTION",zone:"board",art:"recipe",text:"Follow the next printed length, allowing half a peg space of tolerance. A curve may be at most 90°. Glowing targets are legal; an illegal target explains the problem. Confirm spends one action. Undo restores the latest placement and payments until another accepted action occurs.",task:"Use Crews to hire, then Board to inspect a target. Confirm a legal build and try Undo. Your seat stays selected so you can undo. Undo restores the placement and tolls; the hired crew remains paid.",actions:["BUILD","UNDO_PLACEMENT"]},
  {title:"Connections have consequences",phase:"CONSTRUCTION",zone:"board",art:"crossing",text:"Place a station inside any neighborhood to serve it. Different lines of your company transfer only at horizontally/vertically adjacent stations, anywhere on the board. Neighborhood visits award no automatic VP. Never stack pegs. Crossing another color is allowed, but your line cannot cross itself. Joining an opponent station pays $1M once per line/opponent/transfer station; further additions on that line are free there. Every new string contact still costs $1M to its owner, even after transfer access. Your own contacts are free. A geometric crossing alone does not transfer passengers; your lines need horizontally/vertically adjacent stations.",task:"Explore the legal neighborhood holes. Inspect your network connections before confirming."},
  {title:"Count what you delivered",phase:"RESULTS",zone:"results",art:"map",text:"Score completed lines, Engineering goals, connected Destination missions. Longest Network earns 5 VP (3 each if tied), measured along completed segments in peg spaces without reusing a segment. Largest Transfer Station groups horizontally/vertically adjacent pegs across all companies, including the same line. Total each company’s stations across all equally largest transfer stations: the leader earns 6 VP, two tied leaders earn 3 each, three earn 2 each, and four earn none. Unfinished contracts lose points, and your ending cash scores on its band. Results show the breakdown: check what actually scored before planning your next game.",task:"Inspect the score sheets. Replay any lesson, or return to your game."},
];

export function lessonForPhase(phase:string, step:string):number {
  if(phase==="PROCUREMENT")return 2;
  if(phase==="ENGINEERING")return step==="CARD_DRAFT"?3:5;
  if(phase==="SCHEDULING")return 6;
  if(phase==="STARTER_PLACEMENT")return 8;
  if(phase==="CONSTRUCTION")return 6;
  return phase==="RESULTS"||phase==="SCORING"?11:0;
}
